node {
	
	stage('Compilar') {
		echo "Compilando ..."
		sh 'mvn fuentes/pom.xml compile'
	}
	
	stage('Pruebas') {
		echo "Ejecutando pruebas..."
	}
	
	stage('Sonarqube') {
		echo "Analizando codigo con sonarqube"
	}
	
	stage('build') {
		echo "Generando build..."
	}
	
}